/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // ---- Cosmic Essence semantic tokens (Stitch source of truth) ----
        background: '#141315',
        surface: '#141315',
        'surface-dim': '#141315',
        'surface-bright': '#3b383b',
        'surface-container-lowest': '#0f0e10',
        'surface-container-low': '#1d1b1e',
        'surface-container': '#211f22',
        'surface-container-high': '#2b292c',
        'surface-container-highest': '#363437',
        'surface-variant': '#363437',
        'on-surface': '#e6e1e5',
        'on-surface-variant': '#cbc4ce',
        'on-background': '#e6e1e5',
        outline: '#958f98',
        'outline-variant': '#4a454d',
        primary: '#d3beeb',
        'on-primary': '#38294d',
        'primary-container': '#1a0b2e',
        'on-primary-container': '#88769f',
        'primary-fixed': '#eddcff',
        'primary-fixed-dim': '#d3beeb',
        secondary: '#cfc1dd',
        'on-secondary': '#352c42',
        'secondary-container': '#4e455c',
        'on-secondary-container': '#c0b3cf',
        tertiary: '#dbc39f',
        'on-tertiary': '#3c2e14',
        'tertiary-container': '#1c1100',
        'on-tertiary-container': '#8f7b5b',
        error: '#ffb4ab',
        'error-muted': 'rgba(255,180,171,0.12)',
        success: '#22d3ee',
        'success-muted': 'rgba(34,211,238,0.12)',
        'on-error': '#690005',
        // Brand signal accents (purple-led)
        signal: '#c084fc',
        nebula: '#68577e',
        magenta: '#e879f9',
        purple: '#a855f7',
        'line-life': '#a855f7',
        'line-heart': '#f472b6',
        'line-head': '#22d3ee',

        // ---- Legacy namespaces (retuned to Cosmic Essence) ----
        md: {
          background: '#141315',
          surface: '#141315',
          'on-background': '#e6e1e5',
          'on-surface-variant': '#cbc4ce',
          'on-primary-container': '#88769f',
          primary: '#d3beeb',
          'on-primary': '#38294d',
        },
        cosmic: {
          void: '#0f0e10',
          abyss: '#0f0e10',
          night: '#141315',
          nebula: '#1d1b1e',
          haze: '#2b292c',
        },
        stitch: {
          signal: '#22d3ee',
          magenta: '#e879f9',
          violet: '#d3beeb',
          obsidian: '#0f0e10',
        },
        mist: '#e6e1e5',
        ion: '#d3beeb',
      },
      fontFamily: {
        display: ['NotoSerif_700Bold'],
        // Stitch type roles
        headline: ['NotoSerif_700Bold'],
        'headline-md': ['NotoSerif_500Medium'],
        body: ['Inter_400Regular'],
        'body-medium': ['Inter_500Medium'],
        label: ['SpaceGrotesk_600SemiBold'],
        // Legacy aliases
        inter: ['Inter_400Regular'],
        'inter-medium': ['Inter_500Medium'],
        'noto-serif': ['NotoSerif_700Bold'],
        'noto-serif-md': ['NotoSerif_500Medium'],
        'space-grotesk': ['SpaceGrotesk_600SemiBold'],
      },
      boxShadow: {
        glow: '0 0 40px rgba(168,85,247,0.35)',
        'glow-magenta': '0 0 45px rgba(232,121,249,0.40)',
        'glow-sm': '0 0 22px rgba(168,85,247,0.25)',
        aura: '0 0 24px rgba(168,85,247,0.20)',
        nebula: '0 10px 30px rgba(104,87,126,0.35)',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
        '4xl': '48px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '16px',
        'margin-page': '24px',
        'section-gap': '48px',
      },
      borderRadius: {
        glass: '2rem',
        card: '1.5rem',
        pill: '9999px',
        '3xl': '1.75rem',
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
};
